site_name: Cloudbreak 
site_favicon: /images/favicon.png
site_url: http://hortonworks.github.io/cloudbreak-documentation/
repo_url: https://github.com/hortonworks/cloudbreak-documentation
theme_dir: mkdocs_theme
theme_dir: custom_cinder
extra_css:
  - css/extra.css
dev_addr: 0.0.0.0:8000
strict: true
copyright: © 2011-2018 <a href="http://www.hortonworks.com" target="_blank">Hortonworks Inc</a>. All Rights Reserved. | <a href="http://hortonworks.com/privacy-policy/" target="_blank">Privacy Policy</a>
google_analytics: ['UA-22950817-24', 'auto']
markdown_extensions:
  - markdown_include.include
use_directory_urls: false
pages:
    - Intro:
      - Get started: index.md
      - Architecture: architecture.md
      - Security overview: security.md
    - AWS:
      - Launch on AWS: aws-launch.md
      - Create a cluster: aws-create.md
      - Access cluster: aws-clusters-access.md
      - Manage and monitor clusters: aws-clusters-manage.md
      - Access data on S3: aws-data.md
    - Azure:
      - Launch on Azure: azure-launch.md
      - Create a cluster: azure-create.md
      - Access cluster: azure-clusters-access.md
      - Manage and monitor clusters: azure-clusters-manage.md
      - Access data on Azure: azure-data.md
    - GCP:
      - Launch on GCP: gcp-launch.md
      - Create a cluster: gcp-create.md
      - Access cluster: gcp-clusters-access.md
      - Manage and monitor clusters: gcp-clusters-manage.md
    - OpenStack:
      - Launch on OpenStack: os-launch.md
      - Create a cluster: os-create.md
      - Access cluster: os-clusters-access.md
      - Manage and monitor clusters: os-clusters-manage.md
    - Using Cloudbreak:
      - Advanced cluster options:
        - Use custom blueprints: blueprints.md
        - Use custom scripts (recipes): recipes.md
        - Use custom images: images.md
        - Tagging resources: tags.md 
        - Enable Kerberos security: security-kerberos.md
        - Configure autoscaling: autoscaling.md 
        - Register external database: external-db.md  
        - Register external authentication source: external-ldap.md  
        - Register proxy configuration: external-proxy.md  
      - Manage and configure Cloudbreak:  
        - Install Cloudbreak on your own VM: vm-launch.md
        - Upgrade Cloudbreak: cb-upgrade.md 
        - Manage Cloudbreak credentials: cb-credentials.md 
        - Move Cloudbreak instance: cb-migrate.md 
        - Configure LDAP/AD authentication for Cloudbreak: cb-ldap.md  
        - Configure SSL certificates: security-cb-ssl.md
        - Configure outbound internet access and proxy: cb-proxy.md 
        - Restrict inbound access to clusters: security-cb-inbound.md
        - Configure access from custom domains: security-cb-customdom.md
        - Configure external Cloudbreak database: cb-db.md
        - Disable providers: cb-disable-provider.md
        - Modify settings in Cloudbreak Profile: cb-profile.md 
        - Delete Cloudbreak: cb-delete.md
      - Cloudbreak CLI: 
        - Install the CLI: cli-install.md
        - Get started with the CLI: cli-get-started.md
        - CLI Reference: cli-reference.md
      - Troubleshooting: 
        - Cloudbreak logs: trouble-cb-logs.md  
        - Troubleshooting Cloudbreak: trouble-cb.md
        - Troubleshooting cluster creation: trouble-cluster.md
        - Troubleshooting AWS: trouble-aws.md
        - Troubleshooting Azure: trouble-azure.md
        - Troubleshooting GCP: trouble-gcp.md
        - Troubleshooting Cloudbreak CLI: trouble-cli.md
    - More:
      - Release Notes: releasenotes.md
      - FAQs: faq.md 
      - Developer documentation links: dev.md
      - Getting help: get-help.md
      - SmartSense telemetry: smartsense.md
      - Legal:
        - Acknowledgements: acknowledge.md

