site_name: Cloudbreak 
site_favicon: /images/favicon.png
site_url: http://hortonworks.github.io/cloudbreak-documentation/
repo_url: https://github.com/hortonworks/cloudbreak-documentation
theme_dir: mkdocs_theme
theme_dir: custom_cinder
extra_css:
  - css/extra.css
dev_addr: 0.0.0.0:8000
strict: true
copyright: © 2011-2017 <a href="http://www.hortonworks.com" target="_blank">Hortonworks Inc</a>. All Rights Reserved. | <a href="http://hortonworks.com/privacy-policy/" target="_blank">Privacy Policy</a>
google_analytics: ['UA-22950817-24', 'auto']
markdown_extensions:
  - markdown_include.include
use_directory_urls: false
pages:
    - Get Started:
      - Introduction: index.md
      - Architecture: architecture.md
    - AWS:
      - Launch on AWS: aws-launch.md
      - Create a Cluster: aws-create.md
      - Access Data on S3: aws-data.md
    - Azure:
      - Launch on Azure: azure-launch.md
      - Create a Cluster: azure-create.md
      - Access Data on Azure: azure-data.md
    - GCP:
      - Launch on GCP: gcp-launch.md
      - Create a Cluster: gcp-create.md
    - OpenStack:
      - Launch on Open Stack: os-launch.md
      - Create a Cluster: os-create.md
    - Config & Admin:
      - Access Cluster: clusters-access.md
      - Manage and Monitor Cluster: clusters-manage.md
      - Configure Cluster:
        - Blueprints: blueprints.md
        - Templates:
          - Templates for AWS: templates-aws.md
          - Templates for Azure: templates-azure.md
          - Templates for GCP: templates-gcp.md
          - Templates for OpenStack: templates-os.md 
        - Recipes: recipes.md
        - Resource Tagging: tags.md 
        - Auto Scaling: autoscaling.md
        - Custom Cloud Images (TP): images.md
        - Ambari Database (TP): ambari-db.md
        - Cloudbreak Database: cb-db.md
      - Configure Security: 
        - Network and Security: security.md
        - Secure Cloudbreak after Launch: security-cb.md
        - Enable LDAP/AD for Cloudbreak: security-ldap.md
        - Enable Kerberos for Your Cluster: security-kerberos.md
      - Manage Cloudbreak:
        - Manage Cloudbreak Credentials: credentials.md  
        - Manage Your Account: cb-account.md
        - Upgrade Clodbreak: upgrade.md
        - Delete Cloudbreak: delete.md 
        - Install on Your Own VM: vm-launch.md
    - Reference:
      - Release Notes: releasenotes.md
      - Cloudbreak Shell: cb-shell.md
      - Profile File: profile.md
      - FAQs: faq.md 
      - Troubleshooting: 
        - General Troubleshooting: trouble-cb.md
        - Troubleshooting AWS: trouble-aws.md
        - Troubleshooting Azure: trouble-azure.md
        - Troubleshooting GCP: trouble-gcp.md
        - Troubleshooting OpenStack: trouble-os.md
      - Getting Help: get-help.md
      - SmartSense: smartsense.md
      - Developer Docs:
        - Local Development: dev-local-dev.md
        - API: dev-api.md
        - SPI: dev-spi.md
        - Flows: dev-flows.md 

