site_name: Cloudbreak 
site_favicon: /images/favicon.png
site_url: http://hortonworks.github.io/cloudbreak-documentation/
repo_url: https://github.com/hortonworks/cloudbreak-documentation
theme_dir: mkdocs_theme
theme_dir: custom_cinder
extra_css:
  - css/extra.css
dev_addr: 0.0.0.0:8000
strict: true
copyright: © 2011-2017 <a href="http://www.hortonworks.com" target="_blank">Hortonworks Inc</a>. All Rights Reserved. | <a href="http://hortonworks.com/privacy-policy/" target="_blank">Privacy Policy</a>
google_analytics: ['UA-22950817-24', 'auto']
markdown_extensions:
  - markdown_include.include
use_directory_urls: false
pages:
    - Get Started:
      - Introduction: index.md
      - Architecture: architecture.md
      - Release Notes: releasenotes.md
    - AWS:
      - Launch on AWS: aws-launch.md
      - Create a Cluster: aws-create.md
      - Access Cluster: aws-clusters-access.md
      - Access Data on S3: aws-data.md
    - Azure:
      - Launch on Azure: azure-launch.md
      - Create a Cluster: azure-create.md
      - Access Cluster: azure-clusters-access.md
      - Access Data on Azure: azure-data.md
    - GCP:
      - Launch on GCP: gcp-launch.md
      - Create a Cluster: gcp-create.md
      - Access Cluster: gcp-clusters-access.md
    - OpenStack:
      - Launch on Open Stack: os-launch.md
      - Create a Cluster: os-create.md
      - Access Cluster: os-clusters-access.md
    - Config & Admin:
      - Cluster Options:
        - Blueprints: blueprints.md
        - Templates:
          - Templates for AWS: templates-aws.md
          - Templates for Azure: templates-azure.md
          - Templates for GCP: templates-gcp.md
          - Templates for OpenStack: templates-os.md 
        - Recipes: recipes.md
        - Resource Tagging: tags.md 
        - Auto Scaling: autoscaling.md
        - Custom Images: images.md
        - Ambari Database: ambari-db.md
      - Manage and Monitor Clusters: clusters-manage.md
      - Managing Cloudbreak:
        - Install on Your Own VM: vm-launch.md
        - Manage Cloudbreak Credentials: credentials.md  
        - Manage Your Account: cb-account.md
        - Configure Cloudbreak: profile.md
        - Manage Cloudbreak Database: cb-db.md
        - Upgrade Clodbreak: upgrade.md
        - Delete Cloudbreak: delete.md 
      - Security: 
        - Security Overview: security.md
        - Basic Security: security-cb.md
        - LDAP/AD: security-ldap.md
        - Kerberos: security-kerberos.md
    - More:
      - Troubleshooting: 
        - General Troubleshooting: trouble-cb.md
        - Troubleshooting AWS: trouble-aws.md
        - Troubleshooting Azure: trouble-azure.md
        - Troubleshooting GCP: trouble-gcp.md
        - Troubleshooting OpenStack: trouble-os.md
      - Cloudbreak Shell: cb-shell.md
      - Developer:
        - Set up Local Environment: dev-local-dev.md
        - Cloudbreak SPI: dev-spi.md
        - Cloudbreak APIs: dev-api.md
        - Flow Diagrams: dev-flows.md 
      - FAQs: faq.md 
      - Getting Help: get-help.md
      - SmartSense: smartsense.md


